name: Unit Tests 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  pull_request:
  push:
  workflow_dispatch:


env:
  DATADEPS_ALWAYS_ACCEPT: 1
  JIVE_PROCS: 1

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5


      - name: Unit Tests Master Branch
        run: |
          julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.build();'
          julia --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test("LogicCircuits")'
          julia --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test("ProbabilisticCircuits")'
          julia --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test(; coverage=true)'

      - name: Unit Tests Last Version
        run: |
          julia --project -e 'using Pkg; Pkg.develop(PackageSpec(name="LogicCircuits")); Pkg.develop(PackageSpec(name="ProbabilisticCircuits")); Pkg.instantiate(); Pkg.build();'
          julia --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test("LogicCircuits")'
          julia --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test("ProbabilisticCircuits")'
          julia --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test(; coverage=true)'
